### ISSUE TITLE
"Fastglass/Sendgrid" Namespace

### ISSUE THREAD

**Issue by rtblair** [taz77/sendgrid-php-ng#14]
SendGrid has an official repository using the same PHP namespace as this repo (SendGrid). I've seen the history and understand that they come from the same provenance, but the scope of functionality of the two libraries has diverged. While this package currently represents itself to composer users as a replacement for sendgrid/sendgrid-php, that's misleading as the interface for each is different.

So that users can access both libraries alongside one another easily (without having to maintain a fork of either), I suggest modifying the PSR-4 namespace of this repo. `Fastglass/SendGrid` seems appropriate to me, as it matches the composer namespace. Here's my first attempt (https://github.com/taz77/sendgrid-php-ng/compare/master...rtblair:master). Happy to submit a PR if you're interested.

**Comment by taz77** [comment]
Yes, we can use another Namespace, but I would be afraid to remove the replace in the Composer file. If someone is using both libraries at the same time then there is a problem and I would want to know about it.

**Comment by taz77** [comment]
I can change the namespace with version 2.0.0 that is coming for the V3 API re-write. The "replace" needs to remain because you should not be using both API wrappers at one time. If you are, then something is missing or wrong in one of the wrappers and needs to be fixed. Without the "replace" statement, you could use both wrappers at the same time and there could be conflicts being that I use a lot of SendGrids wrapper code in mine. The main difference between the two is the {{sendgrid-php-ng}} uses Guzzle for the HTTP client.

**Comment by rtblair** [comment]
Thanks for your consideration. A bit more about why I believe "replace" should go away as well:

The `sengrid/sendgrid` package (which also lists itself as a replacement for `sendgrid/sendgrid-php`, and also uses the "SendGrid" php namespace) has a different programming interface than `fastglass/sendgrid-php`. This repository does not implement SendGrid mailing features with exactly the same interface, and it also (currently) focuses on a more discrete set of SendGrid API capabilities.

The "replace" declaration tells composer that it should expect the same functionality from `fastglass/sendgrid-php` that it would find in `sendgrid/sendgrid`, so composer would default to skipping the installation of `sendgrid/sendgrid` (even if another package depends on it explicitly). That package would then error out as it calls classes, methods, and functions that don't exist in `fastglass/sendgrid-php`.

FWIW, here's my use case: I run a sprawling Drupal site (https://github.com/nysenate/NYSenate.gov) and my team depends on your Drupal `sendgrid_integration` module (which requires this package) for everything that runs through drupal_mail(). My team is adding a mass emailing feature to our platform. However, we are circumventing `drupal_mail()` entirely, and going directly to the API wrapper for this. We need to leverage the v3 API today because of the superior error reporting, so fastglass/sendgrid-php is not appropriate right now. 

To make this work, we had to patch `sendgrid_integration` so that it uses a fork of `taz77/sendgrid-php-ng` which fully separates the namespaces and removes the `replace` declaration (https://github.com/taz77/sendgrid-php-ng/compare/master...rtblair:master). 

We're perfectly capable of scratching our itch and maintaining the package fork and the module patch; I'm not asking for this out of laziness. But I do think it makes sense on a philosophical level, so I hope you'll consider removing the assertion that this is a full replacement for `sendgrid/sendgrid`. 

In any event, thanks so much for being responsive!

**Comment by taz77** [comment]
@rtblair You may want to check the issue queue. https://github.com/taz77/sendgrid-php-ng/issues/6. The next release of this API wrapper is for V3 API. The Drupal module will also be updated when the work is complete for V3 upgrade. You may note, I am also the maintainer of the Drupal module you are using! I go by Perignon on Drupal.org.

I can see removing the replace when I cut V2. When I started this, it was a complete drop-in replacement for the SendGrid's official PHP wrapper at the time. I forked their code because I wanted to use Guzzle even for D7 and that also made a D8 version of the Drupal module very easy since Guzzle is in D8 core. SendGrid have changed their official PHP code a lot and it broke backward compatibility. In that respect, they are incorrectly using the {{replace}} directive I guess. I have talked to the maintainer of their code a lot - Elmer - but not recently. I like how everything can be just serialized JSON and I am going to be borrowing a lot of their code. I thought about forking their code and swapping out the HTTP client for Guzzle but that would break the Drupal modules because they did not maintain backward compatibility.

My intent is to fully allow all functions of the V3 API. So this would make the wrapper here a complete replacement for Sendgrid's code. I welcome any help getting the V3 branch further along. Between day job, family, and my side business, my time is spread thin.

BTW, have you considered other services for emailing? I found SendGrid's marketing features just far behind the industry normals to use as a mass emailing platform. I am currently using Mailchimp for that purpose.

**Comment by taz77** [comment]
@rtblair Moving namespaces: https://github.com/taz77/sendgrid-php-ng/commit/af45c130521fa18ee89cdc372de950137c988187
